### ISSUE TITLE
Contents page

### ISSUE THREAD

**Issue by JamesBremner** [Zeleska/Nana-doc#2]
There does not seem to be a contents page where the reader can find the docs for a particular widget.

**Comment by Zeleska** [comment]
Viewing any HTML file in any browser should display a navigation menu at the left. It doesn't appear for you?

**Comment by JamesBremner** [comment]
OK, if you say so.  I have not downloaded your code.  You need to provide a website where the html is rendered.  See issues #1 

This issue can be closed.
